
//this make reference to detail of ecah product
export const products=[
      {
        id:1,
        url:"https://s13emagst.akamaized.net/products/2043/2042034/images/res_7ddcd1ea4432163f0dd1e34e37ba5c35.jpg",
        brand:"Apple",
        model:"iPhone 6",
        screenSize:4.7,
        ram:1,
        storage:64,
        os:"ios 8",
        camera:8,
        battery:1650,
        price:150,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
    
      {
        id:2,
        url:"https://s1.flanco.ro/catalog/product/cache/368/image/1000x1000/9df78eab33525d08d6e5fb8d27136e95/1/3/137258_d1.jpg",
        brand:"Apple",
        model:"iPhone 11",
        screenSize:6.1,
        ram:4,
        storage:128,
        os:"ios 13",
        camera:12,
        battery:3000,
        price:650,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
    
      {
        id:3,
        url:"https://s1.flanco.ro/catalog/product/cache/368/image/1000x1000/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone7plusmat_3_2_1.jpg",
        brand:"Apple",
        model:"iPhone 7",
        screenSize:4.7,
        ram:2,
        storage:32,
        os:"ios 10",
        camera:12,
        battery:1960,
        price:350,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
    
      {
        id:4,
        url:"https://images-na.ssl-images-amazon.com/images/I/61YVqHdFRxL._AC_SL1322_.jpg",
        brand:"Samsung",
        model:"Galaxy S10",
        screenSize:6.1,
        ram:8,
        storage:128,
        os:"Android 10",
        camera:16,
        battery:3400,
        price:850,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
    
      {
        id:5,
        url:"https://s1.flanco.ro/catalog/product/cache/368/image/1000x1000/9df78eab33525d08d6e5fb8d27136e95/1/3/136688_13_1.jpg",
        brand:"Samsung",
        model:"Galaxy Note 10",
        screenSize:6.3,
        ram:8,
        storage:256,
        os:"Android 10",
        camera:12,
        battery:3500,
        price:950,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
    
      {
        id:6,
        url:"https://s1.flanco.ro/catalog/product/cache/368/image/1000x1000/9df78eab33525d08d6e5fb8d27136e95/1/2/122088-5_1_1.jpg",
        brand:"Apple",
        model:"iPhone 10",
        screenSize:5.8,
        ram:3,
        storage:64,
        os:"ios 11",
        camera:12,
        battery:2700,
        price:850,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
    
      {
        id:7,
        url:"https://imgaz2.staticbg.com/thumb/large/oaupload/banggood/images/7B/2F/651cca01-fe26-4ea6-872f-e6b23b851eba.jpg",
        brand:"Asus",
        model:"Zenfone max",
        screenSize:5.5,
        ram:3,
        storage:32,
        os:"Android 8",
        camera:13,
        battery:4000,
        price:350,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
    
      {
        id:8,
        url:"https://cdn.tecobuy.co.uk/media/catalog/product/s/a/samsung-galaxy-s20-8gb-128gb-dual-sim-cloud-pink.jpg",
        brand:"Samsung",
        model:"Galaxy S20",
        screenSize:6.9,
        ram:12,
        storage:256,
        os:"Android 10",
        camera:108,
        battery:5000,
        price:1250,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
    
      {
        id:9,
        url:"https://cdn-media.carrefour.ro/media/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/8/3/2/3226872_huawei-telefon-mobil-huawei-p30-pro-dual-sim-256gb-8gb-ram-4g-breathing-crystal-359209.jpg",
        brand:"Huawei",
        model:"P30",
        screenSize:6.1,
        ram:8,
        storage:256,
        os:"Android 9",
        camera:40,
        battery:3600,
        price:950,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
    
      {
        id:10,
        url:"https://s1.flanco.ro/catalog/product/cache/368/image/650x650/9df78eab33525d08d6e5fb8d27136e95/1/2/120174-1.jpg",
        brand:"Nokia",
        model:"6",
        screenSize:5.5,
        ram:3,
        storage:32,
        os:"Android 7.1",
        camera:16,
        battery:3000,
        price:350,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
    
      {
        id:11,
        url:"https://s13emagst.akamaized.net/products/8011/8010787/images/res_761dcdb955c4336235ce3bf53ca28676.jpg",
        brand:"ZTE",
        model:"Blade A610",
        screenSize:5.5,
        ram:4,
        storage:32,
        os:"Android 6",
        camera:13,
        battery:5000,
        price:350,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
    
      {
        id:12,
        url:"https://lcdn.altex.ro/resize/media/catalog/product/S/M/2bd48d28d1c32adea0e55139a4e6434a/SMTMQ7C2RMA-1_7088dc32.jpg",
        brand:"Apple",
        model:"iPhone 8",
        screenSize:4.7,
        ram:2,
        storage:64,
        os:"Android 11",
        camera:12,
        battery:1800,
        price:750,
        inCart:false,
        count: 0,
        total: 0,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      }
];


//object with product main details
export const productDetail={
  id:1,
  url:"https://s12emagst.akamaized.net/products/2043/2042034/images/res_49ff331b8025b7c7b95188a2b5cff86b_full.jpg",
  brand:"Apple",
  model:"iPhone 6",
  screenSize:4.7,
  ram:1,
  storage:64,
  os:"ios 8",
  camera:8,
  battery:1650,
  price:150,
  inCart:false,
  count: 0,
  total: 0,
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia."
}
